version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/include/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get install cmake -y'
      - run:
          name: Installing Valgrind
          command: 'apt-get update && apt-get install valgrind -y'
      - run:
          name: Installing CppCheck
          command: 'apt-get update && sudo apt-get install cppcheck -y'
#      - run:
#          name: CppCheck
#          command: 'cppcheck main.c quick_sort.c visitors.c'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Task testing
          command: './bin/static_tests'
      - run:
          name: Valgrind check
          command: 'valgrind --leak-check=yes ./bin/static_tests'